version: '3.8'

services:
  db:
    image: postgres:14.10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SAuser2025.
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql # Añadir script de inicialización

  app:
    build: .
    environment:
      REDSHIFT_USERNAME: postgres
      REDSHIFT_PASSWORD: SAuser2025.
      REDSHIFT_HOST: db
      REDSHIFT_PORT: 5432
      REDSHIFT_DBNAME: postgres
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data:
